// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAllTWOUqLcvsmjQU_eU5-v271YsotQrcA',
    appId: '1:166531152278:web:3962933b1147bfd16cc5b7',
    messagingSenderId: '166531152278',
    projectId: 'device-streaming-502f92b5',
    authDomain: 'device-streaming-502f92b5.firebaseapp.com',
    storageBucket: 'device-streaming-502f92b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHVJ3ctii6Z-JLXQdRdXEBLKlJj5SeIVU',
    appId: '1:166531152278:android:4c4b41ac4689c9f06cc5b7',
    messagingSenderId: '166531152278',
    projectId: 'device-streaming-502f92b5',
    storageBucket: 'device-streaming-502f92b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ECpXVx3KY14jlh2jFgbf9FFesRiStlQ',
    appId: '1:166531152278:ios:21a42f10ae349bfe6cc5b7',
    messagingSenderId: '166531152278',
    projectId: 'device-streaming-502f92b5',
    storageBucket: 'device-streaming-502f92b5.firebasestorage.app',
    iosBundleId: 'com.example.spotifyyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ECpXVx3KY14jlh2jFgbf9FFesRiStlQ',
    appId: '1:166531152278:ios:21a42f10ae349bfe6cc5b7',
    messagingSenderId: '166531152278',
    projectId: 'device-streaming-502f92b5',
    storageBucket: 'device-streaming-502f92b5.firebasestorage.app',
    iosBundleId: 'com.example.spotifyyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAllTWOUqLcvsmjQU_eU5-v271YsotQrcA',
    appId: '1:166531152278:web:c0bbe8a6c98c53136cc5b7',
    messagingSenderId: '166531152278',
    projectId: 'device-streaming-502f92b5',
    authDomain: 'device-streaming-502f92b5.firebaseapp.com',
    storageBucket: 'device-streaming-502f92b5.firebasestorage.app',
  );
}
